create table student (id int, name char(32), major char(32));
create table grade (course char(32), student_id int, score float);
show tables;
drop table student;
show tables;
create table grade (id int);
drop table t;
show tables;
drop table grade;
drop table student;